name: Go

on:
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: prometheus/promci@52c7012f5f0070d7281b8db4a119e21341d43c91 # v0.4.5
      - uses: ./.github/promci/actions/setup_environment
      - run: make
      - run: git diff --exit-code

  verify-example-configs:
    name: verify
    runs-on: ubuntu-latest
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - run: make build
      - name: Verify example configs
        run: find ./examples -name "*.yml" -print0 | xargs -0 -I % ./yace verify-config -config.file %
